# Generated by Django 3.2.13 on 2022-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playvideopage',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
