# Generated by Django 3.2.13 on 2022-04-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_video', '0002_playvideopage_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playvideopage',
            name='name_subtitle',
        ),
    ]
